server:
  port: 8085
spring:
  application:
    name: spring-cloud-client-feign
  zipKin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:8087
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/