server:
  port: 8087
spring:
  application:
    name: spring-cloud-admin
  zipKin:
    base-url: http://localhost:9411
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/