server:
  port: 8081
spring:
  application:
    name: spring-cloud-server
  boot:
    admin:
      client:
        url: http://${eureka.instance.hostname}:8087  #服务监控地址
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/