server:
  port: 8083
spring:
  application:
    name: spring-cloud-service
  cloud:
    config:
      uri: http://${eureka.instance.hostname}:8888  #配置中心服务地址
      name: testConfig #要抽取配置文件名(无后缀)
      label: master
      profile: prd #指定要激活那个环境的配置文件
  zipKin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/