server:
  port: 8085
spring:
  application:
    name: spring-cloud-client-feign
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/