server:
  port: 8082
spring:
  application:
    name: spring-cloud-service
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/