server:
  port: 8086
spring:
  application:
    name: spring-cloud-zuul
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka
zuul:
  routes:
    api-feign:
      path: /api/feign/**
      serviceId: spring-cloud-client-feign
    api-ribbon:
      path: /api/ribbon/**
      serviceId: spring-cloud-client-ribbon