server:
  port: 9411 #zipKin默认端口
spring:
  application:
    name: spring-cloud-zipKin
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false